# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v9.4.1
_src_path: https://github.com/Tecnativa/doodba-copier-template
backup_dst: ""
cidr_whitelist: null
compose_version: v2+
domains_migration: {}
domains_prod: {}
domains_test: {}
gitlab_url: ""
odoo_dbfilter: ^prod
odoo_initial_lang: en_US
odoo_listdb: true
odoo_listdb_staging: true
odoo_oci_image: ""
odoo_proxy: ""
odoo_version: 18.0
paths_with_crawlers:
  - /web/image/website
paths_without_crawlers:
  - /web
  - /website/info
postgres_dbname: prod
postgres_exposed: false
postgres_username: odoo
postgres_version: "17"
project_author: OdooClaw
project_license: MIT
project_name: odooclaw-odoo
smtp_default_from: ""
smtp_relay_host: ""
use_refurb: false
whitelist_docker_project_devel: odooclaw-odoo
whitelisted_hosts_devel:
  - cdnjs.cloudflare.com
  - fonts.googleapis.com
  - fonts.gstatic.com
  - www.google.com
  - www.googleapis.com
  - www.gravatar.com
whitelisted_hosts_test: []
